### ISSUE TITLE
consider using chiefy/linodego

### ISSUE THREAD

**Issue by displague** [libgolang/docker-volume-linode#1]
https://github.com/chiefy/linodego/ seeks to become an official Linode APIv4 Go client.  It already has some support for volumes, but could use more users and interested developers.

The custom `linode/lib.go` API calls could be replaced or simplified by relying on the linodego client.

This client is also being used in https://github.com/displague/docker-machine-linode and https://github.com/displague/terraform-provider-linode .. The additional eyes and support in the API wrapper will benefit all of those projects.

Thanks
</shameless_plug>

**Comment by ricardorg79** [comment]
This sounds like a good idea.   Right now I'm trying to get Travis-ci to work.  I will tackle this next.

**Comment by displague** [comment]
I've started on a branch -- I'll link you to it.

I don't know if I have the time to see it through.  I notice that you had to use the node hostname in lieu of some other way to determine which node you are running from.

I've started some discussions around this internally.  Relying on the hostname has some potential gotchas.

**Comment by ricardorg79** [comment]
The Linode label is taken from the command line and uses hostname as a fallback.
```
./docker-volume-linode --linode.host=<label> --linode.token=<token> --linode.region<region>
```
Hopefully there is another way to describe the current machine so it doesn't have to rely on command line arguments or hostname.
