### ISSUE TITLE
Create and attach the volume in a single API calls

### ISSUE THREAD

**Issue by displague** [libgolang/docker-volume-linode#2]
The `POST /v4/volumes/` endpoint accepts a Linode ID (Config ID is optional and will be inferred similar to how it will be inferred on the `/boot` endpoint).

This will prevent provisioning a volume if it would ultimately fail to attach.

**Comment by ricardorg79** [comment]
Makes sense!  My reasoning was that creating and attaching were two different steps in the docker API, but it still needs to be attached to be formatted.   I will address it!
